PRACTICE QUESTIONS ON NUMPY

1. Python program to create an array and convert to a desired dimension, as shown below.
  orginal array [[8 9 10 ] [11 12 13]] reshaped array [[8 9] [10 11] [12 13]]

In [5]:
import numpy as np

In [7]:
## r=int(input("Enter the number of rows: "))
c=int(input("Enter the number of columns: "))
print("Enter the values row by row:")
a=np.array([list(map(int, input().split())) for _ in range(r)])
print("Original array:\n",a)
nr=a.reshape(3, 2)
print("\nReshaped array:\n",nr)

Enter the number of rows:  2
Enter the number of columns:  3


Enter the values row by row:


 8 9 10
 11 12 13


Original array:
 [[ 8  9 10]
 [11 12 13]]

Reshaped array:
 [[ 8  9]
 [10 11]
 [12 13]]


2. Create an array and extract particular set of elements from an array as shown below
   orginal array [[8 9] [10 11] [12 13]] Sliced array [9 11]

In [87]:
r=int(input("Enter the number of rows: "))
c=int(input("Enter the number of columns: "))
print("Enter the values row by row:")
a=np.array([list(map(int, input().split())) for _ in range(r)])
print("Original array:\n",a)
s=a[0:2,1:]
print("\nSliced array:\n", s)

Enter the number of rows:  3
Enter the number of columns:  2


Enter the values row by row:


 1 2
 3 4
 5 6


Original array:
 [[1 2]
 [3 4]
 [5 6]]

Sliced array:
 [[2]
 [4]]


Direct Value

In [85]:
a=np.array([[8, 9], [10, 11], [12, 13]])
print("Original array:\n",a)
s=a[0:2,1:]
print("\nSliced array:\n",s)

Original array:
 [[ 8  9]
 [10 11]
 [12 13]]

Sliced array:
 [[ 9]
 [11]]
